export enum PageRoute {
  LANDING = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  LOGOUT = '/logout',
  CREATE_PROJECT = '/create-project',
  IDEA_GENERATOR = '/idea-generator',
  PROJECTS = '/projects',
  RESOURCE_ACCESS = '/resource-access',
  LEARNING_PATH = '/generate-preferences',
  USER_PROFILE = '/profile/:userId',
  CHECKOUT = '/checkout',
  ACTIVATION = '/activation',
  ONBOARDING = '/onboarding',
  DASHBOARD = '/dashboard',
  PROJECT_DETAIL = '/dashboard/projects/:id',
  GENERATED_PATH = '/generated-path',
}
